name: Ubuntu Latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-version: [ "8.2", "8.3" ]

    steps:
      - uses: actions/checkout@v3

      - uses: nanasess/setup-php@v4
        with:
          php-version: ${{ matrix.php-version }}

      - run: composer validate --strict

      - id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - run: composer install --prefer-dist --no-progress

      - run: composer run-script test
